_info = [player] call a3cs_nametag_fnc_getUnitData;
_imie = _info select 0;
_ranga = _info select 1;
sleep 0.5;
cutText ["", "BLACK FADED", 999];
playmusic "IFTrack09";
[0, 0] spawn BIS_fnc_cinemaBorder;
sleep 10;
titleText ["<t font='RobotoCondensedLight' size='2'>Po odparciu radzieckiej agresji na Litwę przyszła pora na odebranie utraconych wcześniej terenów.</t>", "PLAIN",3,true,true];
sleep 6;
titleFadeOut 0.8;
sleep 3;
titleText ["<t font='RobotoCondensedLight' size='2'>Przed rozpoczęciem natarcia lądowego, na tyły wroga zostają zrzucone elitarne odziały spadochroniarzy, których zadaniem będzie sabotaż infrastruktury przeciwnika.</t>", "PLAIN",3,true,true];
sleep 6;
titleFadeOut 0.8;
sleep 3;
titleText ["<t font='RobotoCondensedLight' size='2'>Rozpoczyna się pierwsza faza Operacji Lewiatan.</t>", "PLAIN",3,true,true];
sleep 6;
titleFadeOut 0.8;
sleep 4;
titleText ["","BLACK OUT",2];
2 cutRsc ["RscLogoB","BLACK",0.01];
titleText ["","BLACK IN",2];
sleep 3;
titleText ["","BLACK OUT",2];
sleep 3;
2 cutRsc ["RscLogoA","BLACK",0.01];
titleText ["","BLACK IN",2];
sleep 3;
titleText ["","BLACK OUT",2];
sleep 3;
2 cutFadeOut 0;
titleText ["","BLACK IN",2];
[["Operacja Lewiatan",2,3,4],["Na południe od Prypeci",2,3,4],["25 Kwietnia 1943",2,3,4],[(_ranga + " " + _imie),2,3,4]] spawn BIS_fnc_EXP_camp_SITREP;

 titleCut ["", "BLACK IN", 8];
   a3cs_nametag_displayInterrupt = false;
 "dynamicBlur" ppEffectEnable true;
 "dynamicBlur" ppEffectAdjust [6];
 "dynamicBlur" ppEffectCommit 0;
 "dynamicBlur" ppEffectAdjust [0.0];
 "dynamicBlur" ppEffectCommit 5;
sleep 16;
[1, 1] spawn BIS_fnc_cinemaBorder;
sleep 10;
