[player, 1 ,["ACE_SelfActions","plecak"]] call ace_interact_menu_fnc_removeActionFromObject;
removeBackpack player;
sleep 0.5;
player addBackpack "B_LIB_GER_SapperBackpack_empty";
sleep 0.5;
player addItemToBackpack "ACE_personalAidKit";
sleep 0.1;
for "_i" from 0 to 1 do { player addItemToBackpack "ACE_morphine" };
sleep 0.1;
for "_i" from 0 to 1 do { player addItemToBackpack "ACE_adenosine" };
sleep 0.1;
for "_i" from 0 to 1 do { player addItemToBackpack "ACE_epinephrine" };
sleep 0.1;
for "_i" from 0 to 4 do { player addItemToBackpack "ACE_elasticBandage" };
sleep 0.1;
for "_i" from 0 to 4 do { player addItemToBackpack "ACE_fieldDressing" };
sleep 0.1;
for "_i" from 0 to 14 do { player addItemToBackpack "ACE_packingBandage" };
sleep 0.1;
player addItemToBackpack "ACE_Flashlight_MX991";
sleep 0.1;
player addItemToBackpack "ACE_MapTools";
sleep 0.1;
for "_i" from 0 to 1 do { player addItemToBackpack "ACE_CableTie" };
sleep 0.1;
player addItemToBackpack "ACE_salineIV";
sleep 0.1;
player addItemToBackpack "ACE_EntrenchingTool";
sleep 0.1;
for "_i" from 0 to 4 do { player addItemToBackpack "ACE_splint" };
sleep 0.1;
for "_i" from 0 to 4 do { player addItemToBackpack "ACE_tourniquet" };
sleep 0.1;
player addItemToBackpack "ACE_EarPlugs";
sleep 0.1;
for "_i" from 0 to 2 do { player addItemToBackpack "SmokeShell" };
sleep 0.1;
for "_i" from 0 to 2 do { player addItemToBackpack "SmokeShellGreen" };

