#include "script_component.hpp"
params ["_player"];

private _face = selectRandom [
    WhiteHead_01,
    WhiteHead_02,
    WhiteHead_03,
    WhiteHead_04,
    WhiteHead_05,	
    WhiteHead_06,
    WhiteHead_07,
    WhiteHead_08,
    WhiteHead_09,
    WhiteHead_10,
    WhiteHead_11,
    WhiteHead_12,
    WhiteHead_13,
    WhiteHead_14,
    WhiteHead_15,
    WhiteHead_16,
    WhiteHead_17,	
    WhiteHead_18,
    WhiteHead_19,
    WhiteHead_20,
    WhiteHead_21,
    WhiteHead_24,
    WhiteHead_25,
    WhiteHead_26,	
    WhiteHead_27,
    WhiteHead_28,
    WhiteHead_29,
    WhiteHead_30,
    WhiteHead_31,
    WhiteHead_32,
    LivonianHead_1,
    LivonianHead_2,
    LivonianHead_3,
    LivonianHead_4,
    LivonianHead_5,
    LivonianHead_6,
    LivonianHead_7,
    LivonianHead_8,
    LivonianHead_9,
    LivonianHead_10,
    RussianHead_1,
    RussianHead_2,
    RussianHead_3,
    RussianHead_4,
    RussianHead_5
];

[_player, _face] remoteExec ["setFace", 0, _player];